// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFg0_J6YhwLyW9hHkiJb2Tqu0QSj-75K0',
    appId: '1:938979866094:web:c922eb286aae843181caff',
    messagingSenderId: '938979866094',
    projectId: 'bikri-book',
    authDomain: 'bikri-book.firebaseapp.com',
    storageBucket: 'bikri-book.firebasestorage.app',
    measurementId: 'G-PXGR4VR6DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCftRuj3itFK1Cxobl9CAqRVej-AO36cp8',
    appId: '1:938979866094:android:9a488445c1d86a7281caff',
    messagingSenderId: '938979866094',
    projectId: 'bikri-book',
    storageBucket: 'bikri-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3AoxtPxNPjEk_JMtO5Xl2oeYWWW4Krw',
    appId: '1:938979866094:ios:288c1231fc78b14e81caff',
    messagingSenderId: '938979866094',
    projectId: 'bikri-book',
    storageBucket: 'bikri-book.firebasestorage.app',
    iosBundleId: 'com.example.bikriBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh3AoxtPxNPjEk_JMtO5Xl2oeYWWW4Krw',
    appId: '1:938979866094:ios:288c1231fc78b14e81caff',
    messagingSenderId: '938979866094',
    projectId: 'bikri-book',
    storageBucket: 'bikri-book.firebasestorage.app',
    iosBundleId: 'com.example.bikriBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFg0_J6YhwLyW9hHkiJb2Tqu0QSj-75K0',
    appId: '1:938979866094:web:b14022c66266d01581caff',
    messagingSenderId: '938979866094',
    projectId: 'bikri-book',
    authDomain: 'bikri-book.firebaseapp.com',
    storageBucket: 'bikri-book.firebasestorage.app',
    measurementId: 'G-3Y6ZYWYJ20',
  );
}
