import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/constants/app_colors.dart';
import 'core/providers.dart';
import 'core/services/hive_service.dart';
import 'core/services/preferences_service.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/presentation/pages/phone_login_page.dart';
import 'features/home/presentation/pages/home_page.dart';
import 'features/onboarding/presentation/pages/onboarding_page.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize local DB
  await HiveService.instance.init();

  // Load saved settings
  final shopName = await PreferencesService.getShopName();
  final locale = await PreferencesService.getLocale();
  final shopId = await PreferencesService.getShopId();
  final isOnboarded = await PreferencesService.isOnboarded();
  final currentUser = FirebaseAuth.instance.currentUser;

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: AppColors.primary,
    statusBarIconBrightness: Brightness.light,
  ));

  runApp(
    ProviderScope(
      overrides: [
        settingsProvider.overrideWith(
          (ref) => SettingsNotifier(
            SettingsState(
              locale: locale,
              shopName: shopName,
              shopId: shopId,
            ),
          ),
        ),
      ],
      child: BikriBookApp(
        isLoggedIn: currentUser != null,
        isOnboarded: isOnboarded,
      ),
    ),
  );
}

class BikriBookApp extends ConsumerWidget {
  const BikriBookApp({
    super.key,
    required this.isLoggedIn,
    required this.isOnboarded,
  });

  final bool isLoggedIn;
  final bool isOnboarded;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final settings = ref.watch(settingsProvider);

    Widget home;
    if (!isLoggedIn) {
      home = const PhoneLoginPage();
    } else if (!isOnboarded) {
      home = const OnboardingPage();
    } else {
      home = const HomePage();
    }

    return MaterialApp(
      title: 'Bikri-Book',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      locale: Locale(settings.locale),
      supportedLocales: const [Locale('en'), Locale('hi')],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      home: home,
    );
  }
}